In [2]:
import numpy as np

a = np.array([[1,2,3,4,5], [1,1,1,1,1]])
b = np.array([[1,2,3,4,5], [1,1,1,1,1]])

In [3]:
a.T

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1]])

In [4]:
print(a, b.T)
print(a.T, b)
np.dot(a.T,b)


[[1 2 3 4 5]
 [1 1 1 1 1]] [[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]]
[[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]] [[1 2 3 4 5]
 [1 1 1 1 1]]


array([[ 2,  3,  4,  5,  6],
       [ 3,  5,  7,  9, 11],
       [ 4,  7, 10, 13, 16],
       [ 5,  9, 13, 17, 21],
       [ 6, 11, 16, 21, 26]])